import React,{useState} from "react"; import {Card,Form,Button,Row,Col,Table,Alert,ButtonGroup} from "react-bootstrap"; import {api} from "../api";
export default function DataConsole(){const [token,setToken]=useState(""),[owners,setOwners]=useState([]),[purchases,setPurchases]=useState([]),[routes,setRoutes]=useState([]),[msg,setMsg]=useState("");
 const headers={"X-Admin-Token":token};
 const load=async()=>{try{const [o,p,r]=await Promise.all([api("/api/admin/owners",{headers}),api("/api/admin/purchases",{headers}),api("/api/admin/routes",{headers})]);setOwners(o);setPurchases(p);setRoutes(r);setMsg(`Loaded ${o.length} owners, ${p.length} purchases and ${r.length} routes.`)}catch(e){setMsg(e.message)}};
 const delOwner=async id=>{if(!confirm("Delete this owner? Purchases linked to this owner will also be deleted."))return;await api(`/api/admin/owners/${id}`,{method:"DELETE",headers});load()};
 const delPurchase=async id=>{if(!confirm("Delete this purchase record?"))return;await api(`/api/admin/purchases/${id}`,{method:"DELETE",headers});load()};
 const clear=async()=>{if(!confirm("Delete ALL owners, purchases and route history?"))return;await api("/api/admin/all",{method:"DELETE",headers});load()};
 return <div className="page"><h2>Data Console</h2><p className="text-secondary">This is the backend database viewer. The token is required; do not expose the production admin token to normal users.</p><Row className="g-3 mb-3"><Col md={9}><Form.Control type="password" placeholder="EV_ADMIN_TOKEN" value={token} onChange={e=>setToken(e.target.value)}/></Col><Col md={3}><Button className="w-100" onClick={load}>Load database</Button></Col></Row>{msg&&<Alert>{msg}</Alert>}
 <Card className="shadow-sm border-0 mb-4"><Card.Body><h5>Owners</h5><Table responsive size="sm"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Vehicle</th><th>Battery</th><th>Personal range</th><th></th></tr></thead><tbody>{owners.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.owner_name}</td><td>{o.email}</td><td>{o.vehicle_id}</td><td>{o.battery_pct}%</td><td>{o.personal_range_km||"—"}</td><td><Button size="sm" variant="outline-danger" onClick={()=>delOwner(o.id)}>Delete</Button></td></tr>)}</tbody></Table></Card.Body></Card>
 <Card className="shadow-sm border-0 mb-4"><Card.Body><h5>Purchases</h5><Table responsive size="sm"><thead><tr><th>ID</th><th>Owner</th><th>Plan</th><th>Amount</th><th>Date</th><th></th></tr></thead><tbody>{purchases.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.owner_name} ({p.email})</td><td>{p.plan}</td><td>{p.amount}</td><td>{p.created_at}</td><td><Button size="sm" variant="outline-danger" onClick={()=>delPurchase(p.id)}>Delete</Button></td></tr>)}</tbody></Table></Card.Body></Card>
 <Card className="shadow-sm border-0"><Card.Body><div className="d-flex justify-content-between"><h5>Recent route history</h5><Button size="sm" variant="outline-danger" onClick={clear}>Delete ALL data</Button></div><Table responsive size="sm"><thead><tr><th>Date</th><th>Source</th><th>Destination</th><th>Distance</th><th>Decision</th></tr></thead><tbody>{routes.map(r=><tr key={r.id}><td>{r.created_at}</td><td>{r.source}</td><td>{r.destination}</td><td>{r.distance_km} km</td><td>{r.decision}</td></tr>)}</tbody></Table></Card.Body></Card>
 </div>
}
